#!/usr/bin/env python 

"""
kshd is a daemon, open a tcp connection and listen on a certain port
(default is 44444).
It will excute any command it received and send result out.
"""

import sys, os
from socket import *
import commands

def main():
    host = ''
    port = 44444

    argc = len(sys.argv)
    try:
        if argc == 2:
            port = int(sys.argv[1])
        elif argc > 2:
            raise ValueError()
    except:
        print >> sys.stderr, "Usage:\n     %s [port]\n" % __file__
        sys.exit(1)

    addr = (host, port)
    tcpSerSock = socket(AF_INET, SOCK_STREAM)
    tcpSerSock.bind(addr)
    tcpSerSock.listen(5)

    while True:
        # print 'waiting for connection...'
        tcpCliSock, addr = tcpSerSock.accept()
        # print 'connected from:', addr

        data = tcpCliSock.recv(1024)
        output = commands.getoutput(data.strip())
        tcpCliSock.send(output)

        tcpCliSock.close()

    tcpSerSock.close()

if __name__ == '__main__':
    # do first fork
    try:
        if os.fork() > 0:
            sys.exit(0)
    except OSError, e:
        print >> sys.stderr, "fork #1 failed: %d(%s)\n" % (e.errno, e.strerror)
        sys.exit(1)

    # decouple from parent environment
    os.chdir('/')
    os.setsid()
    os.umask(0)

    # do second fork
    try:
        pid = os.fork() > 0
        if pid > 0:
            sys.exit(0)
    except OSError, e:
        print >> sys.stderr, "fork #2 failed: %d(%s)\n" % (e.errno, e.strerror)
        sys.exit(1)

    main()

